export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
export const REGISTER_TOKEN_SECRET = process.env.REGISTER_TOKEN_SECRET;
export const RESET_PASSWORD_TOKEN_SECRET =
  process.env.NEXT_PUBLIC_RESET_PASSWORD_TOKEN_SECRET;
export const ACCESS_TOKEN_EXPIRED = process.env.ACCESS_TOKEN_EXPIRED;
export const REFRESH_TOKEN_EXPIRED = process.env.REFRESH_TOKEN_EXPIRED;
export const REGISTER_TOKEN_EXPIRED = process.env.REGISTER_TOKEN_EXPIRED;
export const RESET_PASSWORD_TOKEN_EXPIRED =
  process.env.RESET_PASSWORD_TOKEN_EXPIRED;
